

token: 490097376:AAGJAjbZJJxihAaxufPGtA4S0_s7jQk5BAs
webhook_url: <webhook_here> #like https://www.weebhook.com
webhook_port: <port_here> #only 443, 80, 88 or 8443.
server_url: <server_url>
server_port: <server_port>
api_url: https://api.coinmarketcap.com/v1/ticker/

convert_currency_commands:
  - usd
  - eur
